CREATE TABLE PRODUTOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(45) NOT NULL,
DESCRICAO VARCHAR(45) NOT NULL,
QUANTIDADE_ESTOQUE FLOAT NOT NULL,
LABORATORIO INT NOT NULL,
CONSTRAINT FK_PRODUTOS_LABORATORIOS FOREIGN KEY (LABORATORIO)
REFERENCES LABORATORIOS
)

CREATE TABLE LABORATORIOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(45) NOT NULL,
CNPJ CHAR(14) NOT NULL,
CONSTRAINT UQ_LABORATORIOS_CNPJ UNIQUE (CNPJ)
)

CREATE TABLE ENDERECOS
(
ID INT PRIMARY KEY IDENTITY,
RUA VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CEP CHAR(8) NOT NULL,
NUMERO VARCHAR(5) NOT NULL,
COMPLEMENTO VARCHAR(200) NULL,
PONTO_REFERENCIA VARCHAR(200) NULL,
CIDADE VARCHAR(100) NOT NULL,
ESTADO CHAR(2) NOT NULL,
)

CREATE TABLE CLIENTES
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(45) NOT NULL,
CPF CHAR(11) NOT NULL,
RG VARCHAR(15) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
TELEFONE2 VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
--ENDERECO INT NOT NULL,
CONSTRAINT UQ_CLIENTES_CPF UNIQUE (CPF),
CONSTRAINT UQ_CLIENTES_EMAIL UNIQUE(EMAIL),
--CONSTRAINT FK_CLIENTES_ENDERECOS FOREIGN KEY (ENDERECO) REFERENCES ENDERECOS
)

CREATE TABLE FUNCIONARIOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(45) NOT NULL,
CPF CHAR(11) NOT NULL,
RG VARCHAR(15) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(30) NOT NULL,
ENDERECO INT NOT NULL,
CONSTRAINT UQ_FUNCIONARIOS_CPF UNIQUE (CPF),
CONSTRAINT UQ_FUNCIONARIOS_EMAIL UNIQUE(EMAIL),
CONSTRAINT FK_FUNCIONARIOS_ENDERECOS FOREIGN KEY (ENDERECO) REFERENCES ENDERECOS
)

CREATE TABLE FORNECEDORES
(
ID INT PRIMARY KEY IDENTITY,
RAZAO_SOCIAL VARCHAR(45) NOT NULL,
CNPJ CHAR(14) NOT NULL,
NOME_CONTATO VARCHAR(20) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL
)

CREATE TABLE LOCACOES
(
ID INT PRIMARY KEY IDENTITY,
DATA_LOCACAO DATETIME2 NOT NULL DEFAULT GETDATE(),
DATA_ESPERADA_DEVOLUCAO DATETIME2 NOT NULL,
DATA_DEVOLUCAO DATETIME2 NULL,
VALOR FLOAT NOT NULL,
VALOR_MULTA FLOAT NOT NULL DEFAULT 0,
CLIENTE INT NOT NULL,
CONSTRAINT FK_LOCACOES_CLIENTES FOREIGN KEY (CLIENTE) REFERENCES CLIENTES
)


CREATE TABLE LOCACOES_FILMES
(
LOCACAO INT,
FILME INT,
CONSTRAINT FK_LOCACOES_FILMES_LOCACOES FOREIGN KEY (LOCACAO) REFERENCES LOCACOES,
CONSTRAINT FK_LOCACOES_FILMES_FILMES FOREIGN KEY (FILME) REFERENCES FILMES,
PRIMARY KEY(LOCACAO,FILME)
)
