﻿CREATE TABLE ESTADOS
(
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(75) NOT NULL,
UF VARCHAR(2) NOT NULL
)
INSERT INTO ESTADOS (NOME, UF) 
VALUES
('Acre', 'AC'),
('Alagoas', 'AL'),
('Amazonas', 'AM'),
('Amapá', 'AP'),
('Bahia', 'BA'),
('Ceará', 'CE'),
('Distrito Federal', 'DF'),
('Espírito Santo','ES'),
('Goiás', 'GO'),
('Maranhão', 'MA'),
('Minas Gerais', 'MG'),
('Mato Grosso do Sul','MS'),
('Mato Grosso', 'MT'),
('Pará', 'PA'),
('Paraíba', 'PB'),
('Pernambuco', 'PE'),
('Piauí', 'PI'),
('Paraná', 'PR'),
('Rio de Janeiro','RJ'),
('Rio Grande do Norte','RN'),
('Rondônia', 'RO'),
('Roraima', 'RR'),
('Rio Grande do Sul', 'RS'),
('Santa Catarina', 'SC'),
('Sergipe', 'SE'),
('São Paulo', 'SP'),
('Tocantins', 'TO')


CREATE TABLE ENDERECOS
(
ID INT PRIMARY KEY IDENTITY,
RUA VARCHAR(100) NOT NULL,
NUMERO VARCHAR(45) NOT NULL,
COMPLEMENTO VARCHAR(45) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
ESTADO INT NOT NULL,
CEP CHAR(8) NOT NULL,

CONSTRAINT FK_ENDERECOS_ESTADOS FOREIGN KEY(ESTADO) REFERENCES ESTADOS
)
INSERT INTO ENDERECOS(RUA,NUMERO,COMPLEMENTO,BAIRRO,CIDADE,ESTADO,CEP) VALUES ('Rua teste','1','complemento teste','bairro teste','cidade teste',24,'89030030')


CREATE TABLE FUNCIONARIOS
(
ID INT IDENTITY PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL,
CPF CHAR(11) NOT NULL,
RG VARCHAR(15) NOT NULL,
ENDERECO INT NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(45) NOT NULL,
ISADMIN BIT NOT NULL DEFAULT 0, --0 = FUNCIONÁRIO; 1 = ADM

CONSTRAINT UQ_FUNCIONARIOS_CPF UNIQUE (CPF),
CONSTRAINT UQ_FUNCIONARIOS_EMAIL UNIQUE (EMAIL),
CONSTRAINT FK_FUNCIONARIOS_ENDERECOS FOREIGN KEY(ENDERECO) REFERENCES ENDERECOS
)																							     
INSERT INTO FUNCIONARIOS(NOME,CPF,RG,ENDERECO,TELEFONE,EMAIL,SENHA,NIVEL_PERMISSAO) VALUES ('ADM','10897426908','5169319',2,'(47)99122-2051','admin@admin.com','admin',1)


CREATE TABLE CLIENTES
(
ID INT IDENTITY PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL,
CPF CHAR(11) NOT NULL,
RG VARCHAR(15) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
TELEFONE2 VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PONTOS_FIDELIDADE INT NOT NULL DEFAULT 0,
ISATIVO BIT NOT NULL DEFAULT 1,

CONSTRAINT UQ_CLIENTES_CPF UNIQUE (CPF),
CONSTRAINT UQ_CLIENTES_EMAIL UNIQUE (EMAIL),
)
INSERT INTO CLIENTES(ID,NOME,CPF,RG,TELEFONE,TELEFONE2,EMAIL) VALUES (0,'CLIENTE_PADRAO','00000000000','0000000','(00)00000-0000','(01)01010-1010','cliente_padrao@clientepadrao.com');

CREATE TABLE FORNECEDORES
(
ID INT PRIMARY KEY IDENTITY,
RAZAO_SOCIAL VARCHAR(100) NOT NULL,
CNPJ CHAR(14) NOT NULL,
NOME_CONTATO VARCHAR(45) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,

CONSTRAINT UQ_FORNECEDORES_CNPJ UNIQUE (CNPJ),
CONSTRAINT UQ_FORNECEDORES_EMAIL UNIQUE (EMAIL)
)


CREATE TABLE FORMAS_PAGAMENTO
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(45) NOT NULL
CONSTRAINT UQ_FORMAS_PAGAMENTO_NOME UNIQUE (NOME)
)


CREATE TABLE LABORATORIOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(100) NOT NULL,
CNPJ CHAR(14) NOT NULL,

CONSTRAINT UQ_LABORATORIOS_CNPJ UNIQUE (CNPJ)
)


CREATE TABLE PRODUTOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(100) NOT NULL,
DESCRICAO VARCHAR(250) NOT NULL,
QUANTIA_ESTOQUE FLOAT NOT NULL,
LUCRO FLOAT NOT NULL,
LABORATORIO INT NOT NULL,

CONSTRAINT FK_PRODUTOS_LABORATORIOS FOREIGN KEY (LABORATORIO) REFERENCES LABORATORIOS
)


CREATE TABLE VENDAS
(
ID INT PRIMARY KEY IDENTITY,
DATA_VENDA DATETIME2 NOT NULL DEFAULT GETDATE(),
CLIENTE INT NOT NULL,
FUNCIONARIO INT NOT NULL,
FORMA_PAGAMENTO INT NOT NULL,
VALOR_TOTAL FLOAT NOT NULL,

CONSTRAINT FK_VENDAS_FUNCIONARIOS FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIOS,
CONSTRAINT FK_VENDAS_CLIENTES FOREIGN KEY (CLIENTE) REFERENCES CLIENTES,
CONSTRAINT FK_VENDAS_FORMAS_PAGAMENTO FOREIGN KEY (FORMA_PAGAMENTO) REFERENCES FORMAS_PAGAMENTO,
)


CREATE TABLE COMPRAS
(
ID INT PRIMARY KEY IDENTITY,
DATA_COMPRA DATETIME2 NOT NULL DEFAULT GETDATE(),
VALOR_TOTAL FLOAT NOT NULL,
FORNECEDOR INT NOT NULL,
FUNCIONARIO INT NOT NULL,

CONSTRAINT FK_COMPRAS_FORNECEDORES FOREIGN KEY (FORNECEDOR) REFERENCES FORNECEDORES,
CONSTRAINT FK_COMPRAS_FUNCIONARIO FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIOS
)


CREATE TABLE PRODUTOS_VENDAS
(
PRODUTO INT NOT NULL,
VENDA INT NOT NULL,
QUANTIDADE_VENDIDA FLOAT NOT NULL,
VALOR_UNITARIO FLOAT NOT NULL,

CONSTRAINT FK_PRODUTOS_VENDAS_PRODUTO FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS,
CONSTRAINT FK_PRODUTOS_VENDAS_VENDA FOREIGN KEY (VENDA) REFERENCES VENDAS,
PRIMARY KEY (PRODUTO,VENDA)
)


CREATE TABLE PRODUTOS_COMPRAS
(
PRODUTO INT NOT NULL,
COMPRA INT NOT NULL,
QUANTIDADE_COMPRADA FLOAT NOT NULL,
VALOR_UNITARIO FLOAT NOT NULL,

CONSTRAINT FK_PRODUTOS_COMPRAS_PRODUTOS FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS,
CONSTRAINT FK_PRODUTOS_COMPRAS_COMPRAS FOREIGN KEY (COMPRA) REFERENCES COMPRAS,
PRIMARY KEY (PRODUTO,COMPRA)
)